CREATE DATABASE IF NOT EXISTS week9_security DEFAULT CHARACTER SET utf8mb4;
USE week9_security;

DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled TINYINT NOT NULL DEFAULT 1
);
